// SPDX-License-Identifier: GPL-3.0-or-later

/// Country names, keyed by ISO 3166-1 alpha-2 country code.
public enum Countries {
    public static let names: [String: String] = [
        "AD": String(localized: "Andorra", bundle: .module),
        "AE": String(localized: "United Arab Emirates", bundle: .module),
        "AF": String(localized: "Afghanistan", bundle: .module),
        "AG": String(localized: "Antigua & Barbuda", bundle: .module),
        "AI": String(localized: "Anguilla", bundle: .module),
        "AL": String(localized: "Albania", bundle: .module),
        "AM": String(localized: "Armenia", bundle: .module),
        "AO": String(localized: "Angola", bundle: .module),
        "AQ": String(localized: "Antarctica", bundle: .module),
        "AR": String(localized: "Argentina", bundle: .module),
        "AS": String(localized: "American Samoa", bundle: .module),
        "AT": String(localized: "Austria", bundle: .module),
        "AU": String(localized: "Australia", bundle: .module),
        "AW": String(localized: "Aruba", bundle: .module),
        "AX": String(localized: "Åland Islands", bundle: .module),
        "AZ": String(localized: "Azerbaijan", bundle: .module),
        "BA": String(localized: "Bosnia & Herzegovina", bundle: .module),
        "BB": String(localized: "Barbados", bundle: .module),
        "BD": String(localized: "Bangladesh", bundle: .module),
        "BE": String(localized: "Belgium", bundle: .module),
        "BF": String(localized: "Burkina Faso", bundle: .module),
        "BG": String(localized: "Bulgaria", bundle: .module),
        "BH": String(localized: "Bahrain", bundle: .module),
        "BI": String(localized: "Burundi", bundle: .module),
        "BJ": String(localized: "Benin", bundle: .module),
        "BL": String(localized: "Saint Barthelemy", bundle: .module),
        "BM": String(localized: "Bermuda", bundle: .module),
        "BN": String(localized: "Brunei Darussalam", bundle: .module),
        "BO": String(localized: "Bolivia", bundle: .module),
        "BQ": String(localized: "Bonaire, Sint Eustatius and Saba", bundle: .module),
        "BR": String(localized: "Brazil", bundle: .module),
        "BS": String(localized: "Bahamas", bundle: .module),
        "BT": String(localized: "Bhutan", bundle: .module),
        "BV": String(localized: "Bouvet Island", bundle: .module),
        "BW": String(localized: "Botswana", bundle: .module),
        "BY": String(localized: "Belarus", bundle: .module),
        "BZ": String(localized: "Belize", bundle: .module),
        "CA": String(localized: "Canada", bundle: .module),
        "CC": String(localized: "Cocos (Keeling) Islands", bundle: .module),
        "CD": String(localized: "Democratic Republic of Congo", bundle: .module),
        "CF": String(localized: "Central African Republic", bundle: .module),
        "CG": String(localized: "Congo", bundle: .module),
        "CH": String(localized: "Switzerland", bundle: .module),
        "CI": String(localized: "Ivory Coast", bundle: .module),
        "CK": String(localized: "Cook Islands", bundle: .module),
        "CL": String(localized: "Chile", bundle: .module),
        "CM": String(localized: "Cameroon", bundle: .module),
        "CN": String(localized: "China", bundle: .module),
        "CO": String(localized: "Colombia", bundle: .module),
        "CR": String(localized: "Costa Rica", bundle: .module),
        "CU": String(localized: "Cuba", bundle: .module),
        "CV": String(localized: "Cabo Verde", bundle: .module),
        "CW": String(localized: "Curaçao", bundle: .module),
        "CX": String(localized: "Christmas Island", bundle: .module),
        "CY": String(localized: "Cyprus", bundle: .module),
        "CZ": String(localized: "Czechia", bundle: .module),
        "DE": String(localized: "Germany", bundle: .module),
        "DJ": String(localized: "Djibouti", bundle: .module),
        "DK": String(localized: "Denmark", bundle: .module),
        "DM": String(localized: "Dominica", bundle: .module),
        "DO": String(localized: "Dominican Republic", bundle: .module),
        "DZ": String(localized: "Algeria", bundle: .module),
        "EC": String(localized: "Ecuador", bundle: .module),
        "EE": String(localized: "Estonia", bundle: .module),
        "EG": String(localized: "Egypt", bundle: .module),
        "EH": String(localized: "Western Sahara", bundle: .module),
        "ER": String(localized: "Eritrea", bundle: .module),
        "ES": String(localized: "Spain", bundle: .module),
        "ET": String(localized: "Ethiopia", bundle: .module),
        "EU": String(localized: "Europe", bundle: .module),
        "FI": String(localized: "Finland", bundle: .module),
        "FJ": String(localized: "Fiji", bundle: .module),
        "FK": String(localized: "Falkland Islands (Malvinas)", bundle: .module),
        "FM": String(localized: "Micronesia", bundle: .module),
        "FO": String(localized: "Faroe Islands", bundle: .module),
        "FR": String(localized: "France", bundle: .module),
        "GA": String(localized: "Gabon", bundle: .module),
        "GB": String(localized: "Great Britain", bundle: .module),
        "GD": String(localized: "Grenada", bundle: .module),
        "GE": String(localized: "Georgia", bundle: .module),
        "GF": String(localized: "French Guiana", bundle: .module),
        "GG": String(localized: "Guernsey", bundle: .module),
        "GH": String(localized: "Ghana", bundle: .module),
        "GI": String(localized: "Gibraltar", bundle: .module),
        "GL": String(localized: "Greenland", bundle: .module),
        "GM": String(localized: "Gambia", bundle: .module),
        "GN": String(localized: "Guinea", bundle: .module),
        "GP": String(localized: "Guadeloupe", bundle: .module),
        "GQ": String(localized: "Equatorial Guinea", bundle: .module),
        "GR": String(localized: "Greece", bundle: .module),
        "GS": String(localized: "South Georgia & South Sandwich Islands", bundle: .module),
        "GT": String(localized: "Guatemala", bundle: .module),
        "GU": String(localized: "Guam", bundle: .module),
        "GW": String(localized: "Guinea-Bissau", bundle: .module),
        "GY": String(localized: "Guyana", bundle: .module),
        "HK": String(localized: "Hong Kong", bundle: .module),
        "HM": String(localized: "Heard & McDonald Islands", bundle: .module),
        "HN": String(localized: "Honduras", bundle: .module),
        "HR": String(localized: "Croatia", bundle: .module),
        "HT": String(localized: "Haiti", bundle: .module),
        "HU": String(localized: "Hungary", bundle: .module),
        "ID": String(localized: "Indonesia", bundle: .module),
        "IE": String(localized: "Ireland", bundle: .module),
        "IL": String(localized: "Israel", bundle: .module),
        "IM": String(localized: "Isle of Man", bundle: .module),
        "IN": String(localized: "India", bundle: .module),
        "IO": String(localized: "British Indian Ocean Territory", bundle: .module),
        "IQ": String(localized: "Iraq", bundle: .module),
        "IR": String(localized: "Iran", bundle: .module),
        "IS": String(localized: "Iceland", bundle: .module),
        "IT": String(localized: "Italy", bundle: .module),
        "JE": String(localized: "Jersey", bundle: .module),
        "JM": String(localized: "Jamaica", bundle: .module),
        "JO": String(localized: "Jordan", bundle: .module),
        "JP": String(localized: "Japan", bundle: .module),
        "KE": String(localized: "Kenya", bundle: .module),
        "KG": String(localized: "Kyrgyzstan", bundle: .module),
        "KH": String(localized: "Cambodia", bundle: .module),
        "KI": String(localized: "Kiribati", bundle: .module),
        "KM": String(localized: "Comoros", bundle: .module),
        "KN": String(localized: "Saint Kitts & Nevis", bundle: .module),
        "KP": String(localized: "North Korea", bundle: .module),
        "KR": String(localized: "South Korea", bundle: .module),
        "KW": String(localized: "Kuwait", bundle: .module),
        "KY": String(localized: "Cayman Islands", bundle: .module),
        "KZ": String(localized: "Kazakhstan", bundle: .module),
        "LA": String(localized: "Laos", bundle: .module),
        "LB": String(localized: "Lebanon", bundle: .module),
        "LC": String(localized: "Saint Lucia", bundle: .module),
        "LI": String(localized: "Liechtenstein", bundle: .module),
        "LK": String(localized: "Sri Lanka", bundle: .module),
        "LR": String(localized: "Liberia", bundle: .module),
        "LS": String(localized: "Lesotho", bundle: .module),
        "LT": String(localized: "Lithuania", bundle: .module),
        "LU": String(localized: "Luxembourg", bundle: .module),
        "LV": String(localized: "Latvia", bundle: .module),
        "LY": String(localized: "Libya", bundle: .module),
        "MA": String(localized: "Morocco", bundle: .module),
        "MC": String(localized: "Monaco", bundle: .module),
        "MD": String(localized: "Moldova", bundle: .module),
        "ME": String(localized: "Montenegro", bundle: .module),
        "MF": String(localized: "Saint Martin", bundle: .module),
        "MG": String(localized: "Madagascar", bundle: .module),
        "MH": String(localized: "Marshall Islands", bundle: .module),
        "MK": String(localized: "North Macedonia", bundle: .module),
        "ML": String(localized: "Mali", bundle: .module),
        "MM": String(localized: "Myanmar", bundle: .module),
        "MN": String(localized: "Mongolia", bundle: .module),
        "MO": String(localized: "Macau", bundle: .module),
        "MP": String(localized: "Northern Mariana Islands", bundle: .module),
        "MQ": String(localized: "Martinique", bundle: .module),
        "MR": String(localized: "Mauritania", bundle: .module),
        "MS": String(localized: "Montserrat", bundle: .module),
        "MT": String(localized: "Malta", bundle: .module),
        "MU": String(localized: "Mauritius", bundle: .module),
        "MV": String(localized: "Maldives", bundle: .module),
        "MW": String(localized: "Malawi", bundle: .module),
        "MX": String(localized: "Mexico", bundle: .module),
        "MY": String(localized: "Malaysia", bundle: .module),
        "MZ": String(localized: "Mozambique", bundle: .module),
        "NA": String(localized: "Namibia", bundle: .module),
        "NC": String(localized: "New Caledonia", bundle: .module),
        "NE": String(localized: "Niger", bundle: .module),
        "NF": String(localized: "Norfolk Island", bundle: .module),
        "NG": String(localized: "Nigeria", bundle: .module),
        "NI": String(localized: "Nicaragua", bundle: .module),
        "NL": String(localized: "Netherlands", bundle: .module),
        "NO": String(localized: "Norway", bundle: .module),
        "NP": String(localized: "Nepal", bundle: .module),
        "NR": String(localized: "Nauru", bundle: .module),
        "NU": String(localized: "Niue", bundle: .module),
        "NZ": String(localized: "New Zealand", bundle: .module),
        "OM": String(localized: "Oman", bundle: .module),
        "PA": String(localized: "Panama", bundle: .module),
        "PE": String(localized: "Peru", bundle: .module),
        "PF": String(localized: "French Polynesia", bundle: .module),
        "PG": String(localized: "Papua New Guinea", bundle: .module),
        "PH": String(localized: "Philippines", bundle: .module),
        "PK": String(localized: "Pakistan", bundle: .module),
        "PL": String(localized: "Poland", bundle: .module),
        "PM": String(localized: "Saint Pierre & Miquelon", bundle: .module),
        "PN": String(localized: "Pitcairn", bundle: .module),
        "PR": String(localized: "Puerto Rico", bundle: .module),
        "PS": String(localized: "State of Palestine", bundle: .module),
        "PT": String(localized: "Portugal", bundle: .module),
        "PW": String(localized: "Palau", bundle: .module),
        "PY": String(localized: "Paraguay", bundle: .module),
        "QA": String(localized: "Qatar", bundle: .module),
        "RE": String(localized: "Réunion", bundle: .module),
        "RO": String(localized: "Romania", bundle: .module),
        "RS": String(localized: "Serbia", bundle: .module),
        "RU": String(localized: "Russia", bundle: .module),
        "RW": String(localized: "Rwanda", bundle: .module),
        "SA": String(localized: "Saudi Arabia", bundle: .module),
        "SB": String(localized: "Solomon Islands", bundle: .module),
        "SC": String(localized: "Seychelles", bundle: .module),
        "SD": String(localized: "Sudan", bundle: .module),
        "SE": String(localized: "Sweden", bundle: .module),
        "SG": String(localized: "Singapore", bundle: .module),
        "SH": String(localized: "Saint Helena", bundle: .module),
        "SI": String(localized: "Slovenia", bundle: .module),
        "SJ": String(localized: "Svalbard & Jan Mayen Islands", bundle: .module),
        "SK": String(localized: "Slovak Republic", bundle: .module),
        "SL": String(localized: "Sierra Leone", bundle: .module),
        "SM": String(localized: "San Marino", bundle: .module),
        "SN": String(localized: "Senegal", bundle: .module),
        "SO": String(localized: "Somalia", bundle: .module),
        "SR": String(localized: "Suriname", bundle: .module),
        "SS": String(localized: "South Sudan", bundle: .module),
        "ST": String(localized: "Sao Tome & Principe", bundle: .module),
        "SV": String(localized: "El Salvador", bundle: .module),
        "SX": String(localized: "Sint Maarten", bundle: .module),
        "SY": String(localized: "Syria", bundle: .module),
        "SZ": String(localized: "Eswatini", bundle: .module),
        "TC": String(localized: "Turks & Caicos Islands", bundle: .module),
        "TD": String(localized: "Chad", bundle: .module),
        "TF": String(localized: "French Southern Territories", bundle: .module),
        "TG": String(localized: "Togo", bundle: .module),
        "TH": String(localized: "Thailand", bundle: .module),
        "TJ": String(localized: "Tajikistan", bundle: .module),
        "TK": String(localized: "Tokelau", bundle: .module),
        "TL": String(localized: "Timor-Leste", bundle: .module),
        "TM": String(localized: "Turkmenistan", bundle: .module),
        "TN": String(localized: "Tunisia", bundle: .module),
        "TO": String(localized: "Tonga", bundle: .module),
        "TR": String(localized: "Türkiye", bundle: .module),
        "TT": String(localized: "Trinidad & Tobago", bundle: .module),
        "TV": String(localized: "Tuvalu", bundle: .module),
        "TW": String(localized: "Taiwan", bundle: .module),
        "TZ": String(localized: "Tanzania", bundle: .module),
        "UA": String(localized: "Ukraine", bundle: .module),
        "UG": String(localized: "Uganda", bundle: .module),
        "UM": String(localized: "U.S. Minor Outlying Islands", bundle: .module),
        "US": String(localized: "United States", bundle: .module),
        "UY": String(localized: "Uruguay", bundle: .module),
        "UZ": String(localized: "Uzbekistan", bundle: .module),
        "VA": String(localized: "Holy See (Vatican City State)", bundle: .module),
        "VC": String(localized: "Saint Vincent & The Grenadines", bundle: .module),
        "VE": String(localized: "Venezuela", bundle: .module),
        "VG": String(localized: "British Virgin Islands", bundle: .module),
        "VI": String(localized: "U.S. Virgin Islands", bundle: .module),
        "VN": String(localized: "Viet Nam", bundle: .module),
        "VU": String(localized: "Vanuatu", bundle: .module),
        "WF": String(localized: "Wallis & Futuna", bundle: .module),
        "WS": String(localized: "Samoa", bundle: .module),
        "YE": String(localized: "Yemen", bundle: .module),
        "YT": String(localized: "Mayotte", bundle: .module),
        "ZA": String(localized: "South Africa", bundle: .module),
        "ZM": String(localized: "Zambia", bundle: .module),
        "ZW": String(localized: "Zimbabwe", bundle: .module)
    ]
}
